version: '3.8'
services:
  oss_express_app:
    build: ./express-app
    container_name: oss_express_app
    ports:
      - "80:80"
    depends_on:
      - oss_postgres
    networks:
      - oss_network
    restart: unless-stopped

  oss_postgres:
    image: "postgres:11"
    container_name: oss_postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - "./data/postgresql:/var/lib/postgresql/data"
    networks:
      - oss_network
    ports:
      - "5432:5432"
    restart: unless-stopped

  oss_nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: oss_nginx
    ports:
      - "3000:3000"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - oss_express_app
    networks:
      - oss_network
    restart: unless-stopped

networks:
  oss_network:

